package co.uk.basedapps.vpn.common

import androidx.annotation.DrawableRes
import co.uk.basedapps.vpn.R

enum class CountryFlag(
  @DrawableRes val res: Int
) {
  US(R.drawable.flag_us),
  RU(R.drawable.flag_ru),
  SG(R.drawable.flag_sg),
  AU(R.drawable.flag_au),
  PL(R.drawable.flag_pl),
  DE(R.drawable.flag_de),
  CA(R.drawable.flag_ca),
  FR(R.drawable.flag_fr),
  GB(R.drawable.flag_gb),
  NL(R.drawable.flag_nl),
  MY(R.drawable.flag_my),
  PT(R.drawable.flag_pt),
  ID(R.drawable.flag_id),
  HK(R.drawable.flag_hk),
  BR(R.drawable.flag_br),
  LV(R.drawable.flag_lv),
  FI(R.drawable.flag_fi),
  UA(R.drawable.flag_ua),
  VN(R.drawable.flag_vn),
  JP(R.drawable.flag_jp),
  NG(R.drawable.flag_ng),
  DK(R.drawable.flag_dk),
  IS(R.drawable.flag_is),
  CH(R.drawable.flag_ch),
  AT(R.drawable.flag_at),
  IE(R.drawable.flag_ie),
  GT(R.drawable.flag_gt),
  MX(R.drawable.flag_mx),
  MD(R.drawable.flag_md),
  PK(R.drawable.flag_pk),
  PR(R.drawable.flag_pr),
  ZA(R.drawable.flag_za),
  CZ(R.drawable.flag_cz),
  TR(R.drawable.flag_tr),
  HU(R.drawable.flag_hu),
  CR(R.drawable.flag_cr),
  KR(R.drawable.flag_kr),
  EC(R.drawable.flag_ec),
  CO(R.drawable.flag_co),
  AR(R.drawable.flag_ar),
  TW(R.drawable.flag_tw),
  CL(R.drawable.flag_cl),
  SE(R.drawable.flag_se),
  IN(R.drawable.flag_in),
}
